version: '3.4'

services:
  db:
    image: postgres
    restart: always
    container_name: orderservicedb
    ports:
    - 5440:5432
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_HOST_AUTH_METHOD: "trust"

  carauto.orderservice:
    image: ${DOCKER_REGISTRY-}carautoorderservice
    hostname: orders
    ports:
    - 5410:5000
    - 5480:80
    build:
      context: .
      dockerfile: Dockerfile

networks:
  default:
    external:
      name: carauto-network