global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
- job_name: metrics
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - accountingservice
    - coreservice    
    - interfacesservice
    - messagingservice
    - serviceportalservice
    - socialnetservice
    - kong:8001    